OnlineRetail:
  outputs:
    dev:
      dataset: online_retail
      job_execution_timeout_second: 300
      job_retries: 1
      location: US
      method: service-account
      priority: interactive
      project: master-pager-401705
      threads: 1
      type: bigquery
      keyfile: /opt/airflow/dags/dbts/project-dbt/keyfile.json
  target: dev